name: LSSR
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - albumentations=1.3.1
  - alsa-lib=1.2.8
  - anyio=4.9.0
  - aom=3.3.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attr=2.5.1
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - binutils_impl_linux-64=2.43
  - binutils_linux-64=2.43
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cytoolz=1.0.1
  - dask-core=2025.2.0
  - dbus=1.13.6
  - debugpy=1.8.12
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - ffmpeg=4.4.1
  - fftw=3.3.10
  - filelock=3.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fqdn=1.5.1
  - freeglut=3.2.2
  - freetype=2.12.1
  - fsspec=2025.2.0
  - gcc_impl_linux-64=14.2.0
  - gcc_linux-64=14.2.0
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - giflib=5.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.6.13
  - graphite2=1.3.13
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.41
  - gxx_impl_linux-64=14.2.0
  - gxx_linux-64=14.2.0
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=4.4.1
  - hdf5=1.12.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=70.1
  - idna=3.10
  - imagecodecs-lite=2019.12.3
  - imageio=2.37.0
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.33.0
  - ipywidgets=8.1.6
  - isoduration=20.11.0
  - jack=1.9.22
  - jasper=2.0.33
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.14
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.20.1
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.14
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libcap=2.67
  - libcblas=3.9.0
  - libclang13=15.0.7
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcups=2.3.3
  - libcurand=10.3.5.147
  - libcurl=8.1.2
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdb=6.2.32
  - libdeflate=1.14
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.6.4
  - libffi=3.4.6
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-devel_linux-64=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt=1.11.0
  - libgcrypt-devel=1.11.0
  - libgcrypt-lib=1.11.0
  - libgcrypt-tools=1.11.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.80.2
  - libglu=9.0.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libhwloc=2.9.1
  - libiconv=1.18
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libltdl=2.4.3a
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnghttp2=1.58.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libogg=1.3.5
  - libopencv=4.5.5
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=15.3
  - libprotobuf=3.20.3
  - libsanitizer=14.2.0
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=253
  - libtiff=4.4.0
  - libtool=2.5.4
  - libudev1=253
  - libuuid=2.38.1
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.6
  - networkx=3.4.2
  - notebook=7.4.1
  - notebook-shim=0.2.4
  - nspr=4.36
  - nss=3.100
  - numpy=1.26.4
  - opencv=4.5.5
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.1.8
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - prompt_toolkit=3.0.50
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.3
  - py-opencv=4.5.5
  - pycparser=2.22
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pywavelets=1.8.0
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt-main=5.15.6
  - qudida=0.0.4
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.24.0
  - safetensors=0.5.3
  - scikit-image=0.20.0
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=75.8.2
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - svt-av1=1.1.0
  - sysroot_linux-64=2.17
  - tbb=2021.9.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tifffile=2020.6.3
  - timm=1.0.15
  - tinycss2=1.4.0
  - tk=8.6.13
  - toolz=1.0.0
  - torchaudio=2.5.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2025a
  - uri-template=1.3.0
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - x264=1!161.3030
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - accelerate==1.4.0
      - addict==2.4.0
      - affine==2.4.0
      - aiohappyeyeballs==2.4.8
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.1.0
      - basicsr==1.4.2
      - branca==0.8.1
      - click-plugins==1.1.1
      - cligj==0.7.2
      - clip==1.0
      - cmake==3.31.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - diffusers==0.25.0
      - einops==0.7.0
      - fairscale==0.4.13
      - flatbuffers==25.2.10
      - folium==0.20.0
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - ftfy==6.3.1
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gast==0.6.0
      - geopandas==1.1.1
      - google-pasta==0.2.0
      - grpcio==1.70.0
      - h5py==3.13.0
      - huggingface-hub==0.25.2
      - iopath==0.1.10
      - keras==3.9.2
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - lightning-utilities==0.13.1
      - lit==18.1.8
      - lmdb==1.6.2
      - loralib==0.1.2
      - lpips==0.1.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib-scalebar==0.9.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - namex==0.0.9
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.4.127
      - open-clip-torch==2.20.0
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.15.0
      - peft==0.9.0
      - pillow==9.5.0
      - portalocker==3.1.1
      - propcache==0.3.0
      - protobuf==3.20.3
      - pyogrio==0.11.1
      - pyparsing==3.2.1
      - pyproj==3.7.1
      - pyre-extensions==0.0.29
      - pytorch-lightning==2.0.0
      - pyyaml==6.0
      - rasterio==1.4.3
      - regex==2024.11.6
      - rich==14.0.0
      - sentencepiece==0.2.0
      - shapely==2.1.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tb-nightly==2.20.0a20250304
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - tokenizers==0.13.3
      - tomli==2.2.1
      - torch==2.0.1
      - torchmetrics==1.6.2
      - torchvision==0.15.2
      - transformers==4.28.1
      - triton==2.0.0
      - typing-inspect==0.9.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xformers==0.0.20
      - xyzservices==2025.4.0
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.18.3
